apiVersion: batch/v1
kind: Job
metadata:
  name: hashcat-benchmark
spec:
  template:
    spec:
      containers:
        - name: hashcat-benchmark
          image: stormfirefox1/cse-291-hashcat-benchmark
          env:
            - name: SERVICE
              value: eks
      restartPolicy: Never
  backoffLimit: 5
