FROM k8s.gcr.io/volume-nfs:0.8

COPY nfs-benchmark/server/start-nfs.sh /usr/local/bin/start-nfs.sh
COPY nfs-benchmark/server/run_nfs.sh /usr/local/bin/run_nfs.sh
RUN chmod +x /usr/local/bin/start-nfs.sh /usr/local/bin/run_nfs.sh

RUN mkdir -p /exports

EXPOSE 20048/tcp 2049/tcp 111/tcp

# Launch entrypoint
ENTRYPOINT ["/usr/local/bin/start-nfs.sh"]

CMD ["/exports"]


